-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object exposing (..)


type Address
    = Address


type Capsule
    = Capsule


type CapsuleMission
    = CapsuleMission


type Core
    = Core


type CoreMission
    = CoreMission


type Distance
    = Distance


type Dragon
    = Dragon


type DragonHeatShield
    = DragonHeatShield


type DragonPressurizedCapsule
    = DragonPressurizedCapsule


type DragonThrust
    = DragonThrust


type DragonTrunk
    = DragonTrunk


type DragonTrunkCargo
    = DragonTrunkCargo


type Force
    = Force


type HistoriesResult
    = HistoriesResult


type History
    = History


type Info
    = Info


type InfoLinks
    = InfoLinks


type Landpad
    = Landpad


type Launch
    = Launch


type LaunchLinks
    = LaunchLinks


type LaunchRocket
    = LaunchRocket


type LaunchRocketFairings
    = LaunchRocketFairings


type LaunchRocketFirstStage
    = LaunchRocketFirstStage


type LaunchRocketFirstStageCore
    = LaunchRocketFirstStageCore


type LaunchRocketSecondStage
    = LaunchRocketSecondStage


type LaunchSite
    = LaunchSite


type LaunchTelemetry
    = LaunchTelemetry


type LaunchesPastResult
    = LaunchesPastResult


type Launchpad
    = Launchpad


type Link
    = Link


type Location
    = Location


type Mass
    = Mass


type Mission
    = Mission


type MissionResult
    = MissionResult


type Payload
    = Payload


type PayloadOrbitParams
    = PayloadOrbitParams


type Result
    = Result


type Roadster
    = Roadster


type Rocket
    = Rocket


type RocketEngines
    = RocketEngines


type RocketFirstStage
    = RocketFirstStage


type RocketLandingLegs
    = RocketLandingLegs


type RocketPayloadWeight
    = RocketPayloadWeight


type RocketSecondStage
    = RocketSecondStage


type RocketSecondStagePayloadCompositeFairing
    = RocketSecondStagePayloadCompositeFairing


type RocketSecondStagePayloads
    = RocketSecondStagePayloads


type RocketsResult
    = RocketsResult


type Ship
    = Ship


type ShipLocation
    = ShipLocation


type ShipMission
    = ShipMission


type ShipsResult
    = ShipsResult


type Users
    = Users


type Users_aggregate
    = Users_aggregate


type Users_aggregate_fields
    = Users_aggregate_fields


type Users_max_fields
    = Users_max_fields


type Users_min_fields
    = Users_min_fields


type Users_mutation_response
    = Users_mutation_response


type Volume
    = Volume
