-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import SpaceX.Scalar exposing (defaultCodecs)


type alias Date =
    SpaceX.Scalar.Date


type alias Id =
    SpaceX.Scalar.Id


type alias ObjectID =
    SpaceX.Scalar.ObjectID


type alias Timestamptz =
    SpaceX.Scalar.Timestamptz


type alias Uuid =
    SpaceX.Scalar.Uuid


codecs : SpaceX.Scalar.Codecs Date Id ObjectID Timestamptz Uuid
codecs =
    SpaceX.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecId = defaultCodecs.codecId
        , codecObjectID = defaultCodecs.codecObjectID
        , codecTimestamptz = defaultCodecs.codecTimestamptz
        , codecUuid = defaultCodecs.codecUuid
        }
