-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Core exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
asds_attempts : SelectionSet (Maybe Int) SpaceX.Object.Core
asds_attempts =
    Object.selectionForField "(Maybe Int)" "asds_attempts" [] (Decode.int |> Decode.nullable)


{-| -}
asds_landings : SelectionSet (Maybe Int) SpaceX.Object.Core
asds_landings =
    Object.selectionForField "(Maybe Int)" "asds_landings" [] (Decode.int |> Decode.nullable)


{-| -}
block : SelectionSet (Maybe Int) SpaceX.Object.Core
block =
    Object.selectionForField "(Maybe Int)" "block" [] (Decode.int |> Decode.nullable)


{-| -}
id : SelectionSet (Maybe SpaceX.ScalarCodecs.Id) SpaceX.Object.Core
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
missions :
    SelectionSet decodesTo SpaceX.Object.CapsuleMission
    -> SelectionSet (Maybe (List (Maybe decodesTo))) SpaceX.Object.Core
missions object____ =
    Object.selectionForCompositeField "missions" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
original_launch : SelectionSet (Maybe SpaceX.ScalarCodecs.Date) SpaceX.Object.Core
original_launch =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "original_launch" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
reuse_count : SelectionSet (Maybe Int) SpaceX.Object.Core
reuse_count =
    Object.selectionForField "(Maybe Int)" "reuse_count" [] (Decode.int |> Decode.nullable)


{-| -}
rtls_attempts : SelectionSet (Maybe Int) SpaceX.Object.Core
rtls_attempts =
    Object.selectionForField "(Maybe Int)" "rtls_attempts" [] (Decode.int |> Decode.nullable)


{-| -}
rtls_landings : SelectionSet (Maybe Int) SpaceX.Object.Core
rtls_landings =
    Object.selectionForField "(Maybe Int)" "rtls_landings" [] (Decode.int |> Decode.nullable)


{-| -}
status : SelectionSet (Maybe String) SpaceX.Object.Core
status =
    Object.selectionForField "(Maybe String)" "status" [] (Decode.string |> Decode.nullable)


{-| -}
water_landing : SelectionSet (Maybe Bool) SpaceX.Object.Core
water_landing =
    Object.selectionForField "(Maybe Bool)" "water_landing" [] (Decode.bool |> Decode.nullable)
