-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Dragon exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
active : SelectionSet (Maybe Bool) SpaceX.Object.Dragon
active =
    Object.selectionForField "(Maybe Bool)" "active" [] (Decode.bool |> Decode.nullable)


{-| -}
crew_capacity : SelectionSet (Maybe Int) SpaceX.Object.Dragon
crew_capacity =
    Object.selectionForField "(Maybe Int)" "crew_capacity" [] (Decode.int |> Decode.nullable)


{-| -}
description : SelectionSet (Maybe String) SpaceX.Object.Dragon
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| -}
diameter :
    SelectionSet decodesTo SpaceX.Object.Distance
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
diameter object____ =
    Object.selectionForCompositeField "diameter" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
dry_mass_kg : SelectionSet (Maybe Int) SpaceX.Object.Dragon
dry_mass_kg =
    Object.selectionForField "(Maybe Int)" "dry_mass_kg" [] (Decode.int |> Decode.nullable)


{-| -}
dry_mass_lb : SelectionSet (Maybe Int) SpaceX.Object.Dragon
dry_mass_lb =
    Object.selectionForField "(Maybe Int)" "dry_mass_lb" [] (Decode.int |> Decode.nullable)


{-| -}
first_flight : SelectionSet (Maybe String) SpaceX.Object.Dragon
first_flight =
    Object.selectionForField "(Maybe String)" "first_flight" [] (Decode.string |> Decode.nullable)


{-| -}
heat_shield :
    SelectionSet decodesTo SpaceX.Object.DragonHeatShield
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
heat_shield object____ =
    Object.selectionForCompositeField "heat_shield" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
height_w_trunk :
    SelectionSet decodesTo SpaceX.Object.Distance
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
height_w_trunk object____ =
    Object.selectionForCompositeField "height_w_trunk" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
id : SelectionSet (Maybe SpaceX.ScalarCodecs.Id) SpaceX.Object.Dragon
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
launch_payload_mass :
    SelectionSet decodesTo SpaceX.Object.Mass
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
launch_payload_mass object____ =
    Object.selectionForCompositeField "launch_payload_mass" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
launch_payload_vol :
    SelectionSet decodesTo SpaceX.Object.Volume
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
launch_payload_vol object____ =
    Object.selectionForCompositeField "launch_payload_vol" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) SpaceX.Object.Dragon
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
orbit_duration_yr : SelectionSet (Maybe Int) SpaceX.Object.Dragon
orbit_duration_yr =
    Object.selectionForField "(Maybe Int)" "orbit_duration_yr" [] (Decode.int |> Decode.nullable)


{-| -}
pressurized_capsule :
    SelectionSet decodesTo SpaceX.Object.DragonPressurizedCapsule
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
pressurized_capsule object____ =
    Object.selectionForCompositeField "pressurized_capsule" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
return_payload_mass :
    SelectionSet decodesTo SpaceX.Object.Mass
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
return_payload_mass object____ =
    Object.selectionForCompositeField "return_payload_mass" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
return_payload_vol :
    SelectionSet decodesTo SpaceX.Object.Volume
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
return_payload_vol object____ =
    Object.selectionForCompositeField "return_payload_vol" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
sidewall_angle_deg : SelectionSet (Maybe Float) SpaceX.Object.Dragon
sidewall_angle_deg =
    Object.selectionForField "(Maybe Float)" "sidewall_angle_deg" [] (Decode.float |> Decode.nullable)


{-| -}
thrusters :
    SelectionSet decodesTo SpaceX.Object.DragonThrust
    -> SelectionSet (Maybe (List (Maybe decodesTo))) SpaceX.Object.Dragon
thrusters object____ =
    Object.selectionForCompositeField "thrusters" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
trunk :
    SelectionSet decodesTo SpaceX.Object.DragonTrunk
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Dragon
trunk object____ =
    Object.selectionForCompositeField "trunk" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
type_ : SelectionSet (Maybe String) SpaceX.Object.Dragon
type_ =
    Object.selectionForField "(Maybe String)" "type" [] (Decode.string |> Decode.nullable)


{-| -}
wikipedia : SelectionSet (Maybe String) SpaceX.Object.Dragon
wikipedia =
    Object.selectionForField "(Maybe String)" "wikipedia" [] (Decode.string |> Decode.nullable)
