-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.DragonTrunkCargo exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
solar_array : SelectionSet (Maybe Int) SpaceX.Object.DragonTrunkCargo
solar_array =
    Object.selectionForField "(Maybe Int)" "solar_array" [] (Decode.int |> Decode.nullable)


{-| -}
unpressurized_cargo : SelectionSet (Maybe Bool) SpaceX.Object.DragonTrunkCargo
unpressurized_cargo =
    Object.selectionForField "(Maybe Bool)" "unpressurized_cargo" [] (Decode.bool |> Decode.nullable)
