-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.DragonThrust exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
amount : SelectionSet (Maybe Int) SpaceX.Object.DragonThrust
amount =
    Object.selectionForField "(Maybe Int)" "amount" [] (Decode.int |> Decode.nullable)


{-| -}
fuel_1 : SelectionSet (Maybe String) SpaceX.Object.DragonThrust
fuel_1 =
    Object.selectionForField "(Maybe String)" "fuel_1" [] (Decode.string |> Decode.nullable)


{-| -}
fuel_2 : SelectionSet (Maybe String) SpaceX.Object.DragonThrust
fuel_2 =
    Object.selectionForField "(Maybe String)" "fuel_2" [] (Decode.string |> Decode.nullable)


{-| -}
pods : SelectionSet (Maybe Int) SpaceX.Object.DragonThrust
pods =
    Object.selectionForField "(Maybe Int)" "pods" [] (Decode.int |> Decode.nullable)


{-| -}
thrust :
    SelectionSet decodesTo SpaceX.Object.Force
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.DragonThrust
thrust object____ =
    Object.selectionForCompositeField "thrust" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
type_ : SelectionSet (Maybe String) SpaceX.Object.DragonThrust
type_ =
    Object.selectionForField "(Maybe String)" "type" [] (Decode.string |> Decode.nullable)
