-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.DragonHeatShield exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
dev_partner : SelectionSet (Maybe String) SpaceX.Object.DragonHeatShield
dev_partner =
    Object.selectionForField "(Maybe String)" "dev_partner" [] (Decode.string |> Decode.nullable)


{-| -}
material : SelectionSet (Maybe String) SpaceX.Object.DragonHeatShield
material =
    Object.selectionForField "(Maybe String)" "material" [] (Decode.string |> Decode.nullable)


{-| -}
size_meters : SelectionSet (Maybe Float) SpaceX.Object.DragonHeatShield
size_meters =
    Object.selectionForField "(Maybe Float)" "size_meters" [] (Decode.float |> Decode.nullable)


{-| -}
temp_degrees : SelectionSet (Maybe Int) SpaceX.Object.DragonHeatShield
temp_degrees =
    Object.selectionForField "(Maybe Int)" "temp_degrees" [] (Decode.int |> Decode.nullable)
