-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.DragonTrunk exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
cargo :
    SelectionSet decodesTo SpaceX.Object.DragonTrunkCargo
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.DragonTrunk
cargo object____ =
    Object.selectionForCompositeField "cargo" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
trunk_volume :
    SelectionSet decodesTo SpaceX.Object.Volume
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.DragonTrunk
trunk_volume object____ =
    Object.selectionForCompositeField "trunk_volume" [] object____ (Basics.identity >> Decode.nullable)
