-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Force exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
kN : SelectionSet (Maybe Float) SpaceX.Object.Force
kN =
    Object.selectionForField "(Maybe Float)" "kN" [] (Decode.float |> Decode.nullable)


{-| -}
lbf : SelectionSet (Maybe Float) SpaceX.Object.Force
lbf =
    Object.selectionForField "(Maybe Float)" "lbf" [] (Decode.float |> Decode.nullable)
