-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.History exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
details : SelectionSet (Maybe String) SpaceX.Object.History
details =
    Object.selectionForField "(Maybe String)" "details" [] (Decode.string |> Decode.nullable)


{-| -}
event_date_unix : SelectionSet (Maybe SpaceX.ScalarCodecs.Date) SpaceX.Object.History
event_date_unix =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "event_date_unix" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
event_date_utc : SelectionSet (Maybe SpaceX.ScalarCodecs.Date) SpaceX.Object.History
event_date_utc =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "event_date_utc" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
id : SelectionSet (Maybe SpaceX.ScalarCodecs.Id) SpaceX.Object.History
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
links :
    SelectionSet decodesTo SpaceX.Object.Link
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.History
links object____ =
    Object.selectionForCompositeField "links" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
title : SelectionSet (Maybe String) SpaceX.Object.History
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


{-| -}
flight :
    SelectionSet decodesTo SpaceX.Object.Launch
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.History
flight object____ =
    Object.selectionForCompositeField "flight" [] object____ (Basics.identity >> Decode.nullable)
