-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Landpad exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
attempted_landings : SelectionSet (Maybe String) SpaceX.Object.Landpad
attempted_landings =
    Object.selectionForField "(Maybe String)" "attempted_landings" [] (Decode.string |> Decode.nullable)


{-| -}
details : SelectionSet (Maybe String) SpaceX.Object.Landpad
details =
    Object.selectionForField "(Maybe String)" "details" [] (Decode.string |> Decode.nullable)


{-| -}
full_name : SelectionSet (Maybe String) SpaceX.Object.Landpad
full_name =
    Object.selectionForField "(Maybe String)" "full_name" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet (Maybe SpaceX.ScalarCodecs.Id) SpaceX.Object.Landpad
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
landing_type : SelectionSet (Maybe String) SpaceX.Object.Landpad
landing_type =
    Object.selectionForField "(Maybe String)" "landing_type" [] (Decode.string |> Decode.nullable)


{-| -}
location :
    SelectionSet decodesTo SpaceX.Object.Location
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Landpad
location object____ =
    Object.selectionForCompositeField "location" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
status : SelectionSet (Maybe String) SpaceX.Object.Landpad
status =
    Object.selectionForField "(Maybe String)" "status" [] (Decode.string |> Decode.nullable)


{-| -}
successful_landings : SelectionSet (Maybe String) SpaceX.Object.Landpad
successful_landings =
    Object.selectionForField "(Maybe String)" "successful_landings" [] (Decode.string |> Decode.nullable)


{-| -}
wikipedia : SelectionSet (Maybe String) SpaceX.Object.Landpad
wikipedia =
    Object.selectionForField "(Maybe String)" "wikipedia" [] (Decode.string |> Decode.nullable)
