-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.LaunchRocketSecondStage exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
block : SelectionSet (Maybe Int) SpaceX.Object.LaunchRocketSecondStage
block =
    Object.selectionForField "(Maybe Int)" "block" [] (Decode.int |> Decode.nullable)


{-| -}
payloads :
    SelectionSet decodesTo SpaceX.Object.Payload
    -> SelectionSet (Maybe (List (Maybe decodesTo))) SpaceX.Object.LaunchRocketSecondStage
payloads object____ =
    Object.selectionForCompositeField "payloads" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)
