-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.LaunchRocketFairings exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
recovered : SelectionSet (Maybe Bool) SpaceX.Object.LaunchRocketFairings
recovered =
    Object.selectionForField "(Maybe Bool)" "recovered" [] (Decode.bool |> Decode.nullable)


{-| -}
recovery_attempt : SelectionSet (Maybe Bool) SpaceX.Object.LaunchRocketFairings
recovery_attempt =
    Object.selectionForField "(Maybe Bool)" "recovery_attempt" [] (Decode.bool |> Decode.nullable)


{-| -}
reused : SelectionSet (Maybe Bool) SpaceX.Object.LaunchRocketFairings
reused =
    Object.selectionForField "(Maybe Bool)" "reused" [] (Decode.bool |> Decode.nullable)


{-| -}
ship : SelectionSet (Maybe String) SpaceX.Object.LaunchRocketFairings
ship =
    Object.selectionForField "(Maybe String)" "ship" [] (Decode.string |> Decode.nullable)
