-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.LaunchRocket exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
fairings :
    SelectionSet decodesTo SpaceX.Object.LaunchRocketFairings
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.LaunchRocket
fairings object____ =
    Object.selectionForCompositeField "fairings" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
first_stage :
    SelectionSet decodesTo SpaceX.Object.LaunchRocketFirstStage
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.LaunchRocket
first_stage object____ =
    Object.selectionForCompositeField "first_stage" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
rocket_name : SelectionSet (Maybe String) SpaceX.Object.LaunchRocket
rocket_name =
    Object.selectionForField "(Maybe String)" "rocket_name" [] (Decode.string |> Decode.nullable)


{-| -}
rocket_type : SelectionSet (Maybe String) SpaceX.Object.LaunchRocket
rocket_type =
    Object.selectionForField "(Maybe String)" "rocket_type" [] (Decode.string |> Decode.nullable)


{-| -}
rocket :
    SelectionSet decodesTo SpaceX.Object.Rocket
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.LaunchRocket
rocket object____ =
    Object.selectionForCompositeField "rocket" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
second_stage :
    SelectionSet decodesTo SpaceX.Object.LaunchRocketSecondStage
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.LaunchRocket
second_stage object____ =
    Object.selectionForCompositeField "second_stage" [] object____ (Basics.identity >> Decode.nullable)
