-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.LaunchesPastResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
result :
    SelectionSet decodesTo SpaceX.Object.Result
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.LaunchesPastResult
result object____ =
    Object.selectionForCompositeField "result" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
data :
    SelectionSet decodesTo SpaceX.Object.Launch
    -> SelectionSet (Maybe (List (Maybe decodesTo))) SpaceX.Object.LaunchesPastResult
data object____ =
    Object.selectionForCompositeField "data" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)
