-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.LaunchSite exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
site_id : SelectionSet (Maybe String) SpaceX.Object.LaunchSite
site_id =
    Object.selectionForField "(Maybe String)" "site_id" [] (Decode.string |> Decode.nullable)


{-| -}
site_name_long : SelectionSet (Maybe String) SpaceX.Object.LaunchSite
site_name_long =
    Object.selectionForField "(Maybe String)" "site_name_long" [] (Decode.string |> Decode.nullable)


{-| -}
site_name : SelectionSet (Maybe String) SpaceX.Object.LaunchSite
site_name =
    Object.selectionForField "(Maybe String)" "site_name" [] (Decode.string |> Decode.nullable)
