-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Launchpad exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
attempted_launches : SelectionSet (Maybe Int) SpaceX.Object.Launchpad
attempted_launches =
    Object.selectionForField "(Maybe Int)" "attempted_launches" [] (Decode.int |> Decode.nullable)


{-| -}
details : SelectionSet (Maybe String) SpaceX.Object.Launchpad
details =
    Object.selectionForField "(Maybe String)" "details" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet (Maybe SpaceX.ScalarCodecs.Id) SpaceX.Object.Launchpad
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
location :
    SelectionSet decodesTo SpaceX.Object.Location
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Launchpad
location object____ =
    Object.selectionForCompositeField "location" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) SpaceX.Object.Launchpad
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
status : SelectionSet (Maybe String) SpaceX.Object.Launchpad
status =
    Object.selectionForField "(Maybe String)" "status" [] (Decode.string |> Decode.nullable)


{-| -}
successful_launches : SelectionSet (Maybe Int) SpaceX.Object.Launchpad
successful_launches =
    Object.selectionForField "(Maybe Int)" "successful_launches" [] (Decode.int |> Decode.nullable)


{-| -}
vehicles_launched :
    SelectionSet decodesTo SpaceX.Object.Rocket
    -> SelectionSet (Maybe (List (Maybe decodesTo))) SpaceX.Object.Launchpad
vehicles_launched object____ =
    Object.selectionForCompositeField "vehicles_launched" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
wikipedia : SelectionSet (Maybe String) SpaceX.Object.Launchpad
wikipedia =
    Object.selectionForField "(Maybe String)" "wikipedia" [] (Decode.string |> Decode.nullable)
