-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.LaunchLinks exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
article_link : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
article_link =
    Object.selectionForField "(Maybe String)" "article_link" [] (Decode.string |> Decode.nullable)


{-| -}
flickr_images : SelectionSet (Maybe (List (Maybe String))) SpaceX.Object.LaunchLinks
flickr_images =
    Object.selectionForField "(Maybe (List (Maybe String)))" "flickr_images" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
mission_patch_small : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
mission_patch_small =
    Object.selectionForField "(Maybe String)" "mission_patch_small" [] (Decode.string |> Decode.nullable)


{-| -}
mission_patch : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
mission_patch =
    Object.selectionForField "(Maybe String)" "mission_patch" [] (Decode.string |> Decode.nullable)


{-| -}
presskit : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
presskit =
    Object.selectionForField "(Maybe String)" "presskit" [] (Decode.string |> Decode.nullable)


{-| -}
reddit_campaign : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
reddit_campaign =
    Object.selectionForField "(Maybe String)" "reddit_campaign" [] (Decode.string |> Decode.nullable)


{-| -}
reddit_launch : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
reddit_launch =
    Object.selectionForField "(Maybe String)" "reddit_launch" [] (Decode.string |> Decode.nullable)


{-| -}
reddit_media : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
reddit_media =
    Object.selectionForField "(Maybe String)" "reddit_media" [] (Decode.string |> Decode.nullable)


{-| -}
reddit_recovery : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
reddit_recovery =
    Object.selectionForField "(Maybe String)" "reddit_recovery" [] (Decode.string |> Decode.nullable)


{-| -}
video_link : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
video_link =
    Object.selectionForField "(Maybe String)" "video_link" [] (Decode.string |> Decode.nullable)


{-| -}
wikipedia : SelectionSet (Maybe String) SpaceX.Object.LaunchLinks
wikipedia =
    Object.selectionForField "(Maybe String)" "wikipedia" [] (Decode.string |> Decode.nullable)
