-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.LaunchRocketFirstStageCore exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
block : SelectionSet (Maybe Int) SpaceX.Object.LaunchRocketFirstStageCore
block =
    Object.selectionForField "(Maybe Int)" "block" [] (Decode.int |> Decode.nullable)


{-| -}
core :
    SelectionSet decodesTo SpaceX.Object.Core
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.LaunchRocketFirstStageCore
core object____ =
    Object.selectionForCompositeField "core" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
flight : SelectionSet (Maybe Int) SpaceX.Object.LaunchRocketFirstStageCore
flight =
    Object.selectionForField "(Maybe Int)" "flight" [] (Decode.int |> Decode.nullable)


{-| -}
gridfins : SelectionSet (Maybe Bool) SpaceX.Object.LaunchRocketFirstStageCore
gridfins =
    Object.selectionForField "(Maybe Bool)" "gridfins" [] (Decode.bool |> Decode.nullable)


{-| -}
land_success : SelectionSet (Maybe Bool) SpaceX.Object.LaunchRocketFirstStageCore
land_success =
    Object.selectionForField "(Maybe Bool)" "land_success" [] (Decode.bool |> Decode.nullable)


{-| -}
landing_intent : SelectionSet (Maybe Bool) SpaceX.Object.LaunchRocketFirstStageCore
landing_intent =
    Object.selectionForField "(Maybe Bool)" "landing_intent" [] (Decode.bool |> Decode.nullable)


{-| -}
landing_type : SelectionSet (Maybe String) SpaceX.Object.LaunchRocketFirstStageCore
landing_type =
    Object.selectionForField "(Maybe String)" "landing_type" [] (Decode.string |> Decode.nullable)


{-| -}
landing_vehicle : SelectionSet (Maybe String) SpaceX.Object.LaunchRocketFirstStageCore
landing_vehicle =
    Object.selectionForField "(Maybe String)" "landing_vehicle" [] (Decode.string |> Decode.nullable)


{-| -}
legs : SelectionSet (Maybe Bool) SpaceX.Object.LaunchRocketFirstStageCore
legs =
    Object.selectionForField "(Maybe Bool)" "legs" [] (Decode.bool |> Decode.nullable)


{-| -}
reused : SelectionSet (Maybe Bool) SpaceX.Object.LaunchRocketFirstStageCore
reused =
    Object.selectionForField "(Maybe Bool)" "reused" [] (Decode.bool |> Decode.nullable)
