-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Mission exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
description : SelectionSet (Maybe String) SpaceX.Object.Mission
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet (Maybe SpaceX.ScalarCodecs.Id) SpaceX.Object.Mission
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
manufacturers : SelectionSet (Maybe (List (Maybe String))) SpaceX.Object.Mission
manufacturers =
    Object.selectionForField "(Maybe (List (Maybe String)))" "manufacturers" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) SpaceX.Object.Mission
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
twitter : SelectionSet (Maybe String) SpaceX.Object.Mission
twitter =
    Object.selectionForField "(Maybe String)" "twitter" [] (Decode.string |> Decode.nullable)


{-| -}
website : SelectionSet (Maybe String) SpaceX.Object.Mission
website =
    Object.selectionForField "(Maybe String)" "website" [] (Decode.string |> Decode.nullable)


{-| -}
wikipedia : SelectionSet (Maybe String) SpaceX.Object.Mission
wikipedia =
    Object.selectionForField "(Maybe String)" "wikipedia" [] (Decode.string |> Decode.nullable)


{-| -}
payloads :
    SelectionSet decodesTo SpaceX.Object.Payload
    -> SelectionSet (Maybe (List (Maybe decodesTo))) SpaceX.Object.Mission
payloads object____ =
    Object.selectionForCompositeField "payloads" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)
