-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.PayloadOrbitParams exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
apoapsis_km : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
apoapsis_km =
    Object.selectionForField "(Maybe Float)" "apoapsis_km" [] (Decode.float |> Decode.nullable)


{-| -}
arg_of_pericenter : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
arg_of_pericenter =
    Object.selectionForField "(Maybe Float)" "arg_of_pericenter" [] (Decode.float |> Decode.nullable)


{-| -}
eccentricity : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
eccentricity =
    Object.selectionForField "(Maybe Float)" "eccentricity" [] (Decode.float |> Decode.nullable)


{-| -}
epoch : SelectionSet (Maybe SpaceX.ScalarCodecs.Date) SpaceX.Object.PayloadOrbitParams
epoch =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "epoch" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
inclination_deg : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
inclination_deg =
    Object.selectionForField "(Maybe Float)" "inclination_deg" [] (Decode.float |> Decode.nullable)


{-| -}
lifespan_years : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
lifespan_years =
    Object.selectionForField "(Maybe Float)" "lifespan_years" [] (Decode.float |> Decode.nullable)


{-| -}
longitude : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
longitude =
    Object.selectionForField "(Maybe Float)" "longitude" [] (Decode.float |> Decode.nullable)


{-| -}
mean_anomaly : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
mean_anomaly =
    Object.selectionForField "(Maybe Float)" "mean_anomaly" [] (Decode.float |> Decode.nullable)


{-| -}
mean_motion : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
mean_motion =
    Object.selectionForField "(Maybe Float)" "mean_motion" [] (Decode.float |> Decode.nullable)


{-| -}
periapsis_km : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
periapsis_km =
    Object.selectionForField "(Maybe Float)" "periapsis_km" [] (Decode.float |> Decode.nullable)


{-| -}
period_min : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
period_min =
    Object.selectionForField "(Maybe Float)" "period_min" [] (Decode.float |> Decode.nullable)


{-| -}
raan : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
raan =
    Object.selectionForField "(Maybe Float)" "raan" [] (Decode.float |> Decode.nullable)


{-| -}
reference_system : SelectionSet (Maybe String) SpaceX.Object.PayloadOrbitParams
reference_system =
    Object.selectionForField "(Maybe String)" "reference_system" [] (Decode.string |> Decode.nullable)


{-| -}
regime : SelectionSet (Maybe String) SpaceX.Object.PayloadOrbitParams
regime =
    Object.selectionForField "(Maybe String)" "regime" [] (Decode.string |> Decode.nullable)


{-| -}
semi_major_axis_km : SelectionSet (Maybe Float) SpaceX.Object.PayloadOrbitParams
semi_major_axis_km =
    Object.selectionForField "(Maybe Float)" "semi_major_axis_km" [] (Decode.float |> Decode.nullable)
