-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Payload exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
customers : SelectionSet (Maybe (List (Maybe String))) SpaceX.Object.Payload
customers =
    Object.selectionForField "(Maybe (List (Maybe String)))" "customers" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
id : SelectionSet (Maybe SpaceX.ScalarCodecs.Id) SpaceX.Object.Payload
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
manufacturer : SelectionSet (Maybe String) SpaceX.Object.Payload
manufacturer =
    Object.selectionForField "(Maybe String)" "manufacturer" [] (Decode.string |> Decode.nullable)


{-| -}
nationality : SelectionSet (Maybe String) SpaceX.Object.Payload
nationality =
    Object.selectionForField "(Maybe String)" "nationality" [] (Decode.string |> Decode.nullable)


{-| -}
norad_id : SelectionSet (Maybe (List (Maybe Int))) SpaceX.Object.Payload
norad_id =
    Object.selectionForField "(Maybe (List (Maybe Int)))" "norad_id" [] (Decode.int |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
orbit_params :
    SelectionSet decodesTo SpaceX.Object.PayloadOrbitParams
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Payload
orbit_params object____ =
    Object.selectionForCompositeField "orbit_params" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
orbit : SelectionSet (Maybe String) SpaceX.Object.Payload
orbit =
    Object.selectionForField "(Maybe String)" "orbit" [] (Decode.string |> Decode.nullable)


{-| -}
payload_mass_kg : SelectionSet (Maybe Float) SpaceX.Object.Payload
payload_mass_kg =
    Object.selectionForField "(Maybe Float)" "payload_mass_kg" [] (Decode.float |> Decode.nullable)


{-| -}
payload_mass_lbs : SelectionSet (Maybe Float) SpaceX.Object.Payload
payload_mass_lbs =
    Object.selectionForField "(Maybe Float)" "payload_mass_lbs" [] (Decode.float |> Decode.nullable)


{-| -}
payload_type : SelectionSet (Maybe String) SpaceX.Object.Payload
payload_type =
    Object.selectionForField "(Maybe String)" "payload_type" [] (Decode.string |> Decode.nullable)


{-| -}
reused : SelectionSet (Maybe Bool) SpaceX.Object.Payload
reused =
    Object.selectionForField "(Maybe Bool)" "reused" [] (Decode.bool |> Decode.nullable)
