-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Roadster exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
apoapsis_au : SelectionSet (Maybe Float) SpaceX.Object.Roadster
apoapsis_au =
    Object.selectionForField "(Maybe Float)" "apoapsis_au" [] (Decode.float |> Decode.nullable)


{-| -}
details : SelectionSet (Maybe String) SpaceX.Object.Roadster
details =
    Object.selectionForField "(Maybe String)" "details" [] (Decode.string |> Decode.nullable)


{-| -}
earth_distance_km : SelectionSet (Maybe Float) SpaceX.Object.Roadster
earth_distance_km =
    Object.selectionForField "(Maybe Float)" "earth_distance_km" [] (Decode.float |> Decode.nullable)


{-| -}
earth_distance_mi : SelectionSet (Maybe Float) SpaceX.Object.Roadster
earth_distance_mi =
    Object.selectionForField "(Maybe Float)" "earth_distance_mi" [] (Decode.float |> Decode.nullable)


{-| -}
eccentricity : SelectionSet (Maybe Float) SpaceX.Object.Roadster
eccentricity =
    Object.selectionForField "(Maybe Float)" "eccentricity" [] (Decode.float |> Decode.nullable)


{-| -}
epoch_jd : SelectionSet (Maybe Float) SpaceX.Object.Roadster
epoch_jd =
    Object.selectionForField "(Maybe Float)" "epoch_jd" [] (Decode.float |> Decode.nullable)


{-| -}
inclination : SelectionSet (Maybe Float) SpaceX.Object.Roadster
inclination =
    Object.selectionForField "(Maybe Float)" "inclination" [] (Decode.float |> Decode.nullable)


{-| -}
launch_date_unix : SelectionSet (Maybe SpaceX.ScalarCodecs.Date) SpaceX.Object.Roadster
launch_date_unix =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "launch_date_unix" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
launch_date_utc : SelectionSet (Maybe SpaceX.ScalarCodecs.Date) SpaceX.Object.Roadster
launch_date_utc =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "launch_date_utc" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
launch_mass_kg : SelectionSet (Maybe Int) SpaceX.Object.Roadster
launch_mass_kg =
    Object.selectionForField "(Maybe Int)" "launch_mass_kg" [] (Decode.int |> Decode.nullable)


{-| -}
launch_mass_lbs : SelectionSet (Maybe Int) SpaceX.Object.Roadster
launch_mass_lbs =
    Object.selectionForField "(Maybe Int)" "launch_mass_lbs" [] (Decode.int |> Decode.nullable)


{-| -}
longitude : SelectionSet (Maybe Float) SpaceX.Object.Roadster
longitude =
    Object.selectionForField "(Maybe Float)" "longitude" [] (Decode.float |> Decode.nullable)


{-| -}
mars_distance_km : SelectionSet (Maybe Float) SpaceX.Object.Roadster
mars_distance_km =
    Object.selectionForField "(Maybe Float)" "mars_distance_km" [] (Decode.float |> Decode.nullable)


{-| -}
mars_distance_mi : SelectionSet (Maybe Float) SpaceX.Object.Roadster
mars_distance_mi =
    Object.selectionForField "(Maybe Float)" "mars_distance_mi" [] (Decode.float |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) SpaceX.Object.Roadster
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
norad_id : SelectionSet (Maybe Int) SpaceX.Object.Roadster
norad_id =
    Object.selectionForField "(Maybe Int)" "norad_id" [] (Decode.int |> Decode.nullable)


{-| -}
orbit_type : SelectionSet (Maybe Float) SpaceX.Object.Roadster
orbit_type =
    Object.selectionForField "(Maybe Float)" "orbit_type" [] (Decode.float |> Decode.nullable)


{-| -}
periapsis_arg : SelectionSet (Maybe Float) SpaceX.Object.Roadster
periapsis_arg =
    Object.selectionForField "(Maybe Float)" "periapsis_arg" [] (Decode.float |> Decode.nullable)


{-| -}
periapsis_au : SelectionSet (Maybe Float) SpaceX.Object.Roadster
periapsis_au =
    Object.selectionForField "(Maybe Float)" "periapsis_au" [] (Decode.float |> Decode.nullable)


{-| -}
period_days : SelectionSet (Maybe Float) SpaceX.Object.Roadster
period_days =
    Object.selectionForField "(Maybe Float)" "period_days" [] (Decode.float |> Decode.nullable)


{-| -}
semi_major_axis_au : SelectionSet (Maybe Float) SpaceX.Object.Roadster
semi_major_axis_au =
    Object.selectionForField "(Maybe Float)" "semi_major_axis_au" [] (Decode.float |> Decode.nullable)


{-| -}
speed_kph : SelectionSet (Maybe Float) SpaceX.Object.Roadster
speed_kph =
    Object.selectionForField "(Maybe Float)" "speed_kph" [] (Decode.float |> Decode.nullable)


{-| -}
speed_mph : SelectionSet (Maybe Float) SpaceX.Object.Roadster
speed_mph =
    Object.selectionForField "(Maybe Float)" "speed_mph" [] (Decode.float |> Decode.nullable)


{-| -}
wikipedia : SelectionSet (Maybe String) SpaceX.Object.Roadster
wikipedia =
    Object.selectionForField "(Maybe String)" "wikipedia" [] (Decode.string |> Decode.nullable)
