-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.RocketPayloadWeight exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
id : SelectionSet (Maybe String) SpaceX.Object.RocketPayloadWeight
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


{-| -}
kg : SelectionSet (Maybe Int) SpaceX.Object.RocketPayloadWeight
kg =
    Object.selectionForField "(Maybe Int)" "kg" [] (Decode.int |> Decode.nullable)


{-| -}
lb : SelectionSet (Maybe Int) SpaceX.Object.RocketPayloadWeight
lb =
    Object.selectionForField "(Maybe Int)" "lb" [] (Decode.int |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) SpaceX.Object.RocketPayloadWeight
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
