-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.RocketSecondStagePayloads exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
option_1 : SelectionSet (Maybe String) SpaceX.Object.RocketSecondStagePayloads
option_1 =
    Object.selectionForField "(Maybe String)" "option_1" [] (Decode.string |> Decode.nullable)


{-| -}
composite_fairing :
    SelectionSet decodesTo SpaceX.Object.RocketSecondStagePayloadCompositeFairing
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.RocketSecondStagePayloads
composite_fairing object____ =
    Object.selectionForCompositeField "composite_fairing" [] object____ (Basics.identity >> Decode.nullable)
