-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.RocketEngines exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
number : SelectionSet (Maybe Int) SpaceX.Object.RocketEngines
number =
    Object.selectionForField "(Maybe Int)" "number" [] (Decode.int |> Decode.nullable)


{-| -}
type_ : SelectionSet (Maybe String) SpaceX.Object.RocketEngines
type_ =
    Object.selectionForField "(Maybe String)" "type" [] (Decode.string |> Decode.nullable)


{-| -}
version : SelectionSet (Maybe String) SpaceX.Object.RocketEngines
version =
    Object.selectionForField "(Maybe String)" "version" [] (Decode.string |> Decode.nullable)


{-| -}
layout : SelectionSet (Maybe String) SpaceX.Object.RocketEngines
layout =
    Object.selectionForField "(Maybe String)" "layout" [] (Decode.string |> Decode.nullable)


{-| -}
engine_loss_max : SelectionSet (Maybe String) SpaceX.Object.RocketEngines
engine_loss_max =
    Object.selectionForField "(Maybe String)" "engine_loss_max" [] (Decode.string |> Decode.nullable)


{-| -}
propellant_1 : SelectionSet (Maybe String) SpaceX.Object.RocketEngines
propellant_1 =
    Object.selectionForField "(Maybe String)" "propellant_1" [] (Decode.string |> Decode.nullable)


{-| -}
propellant_2 : SelectionSet (Maybe String) SpaceX.Object.RocketEngines
propellant_2 =
    Object.selectionForField "(Maybe String)" "propellant_2" [] (Decode.string |> Decode.nullable)


{-| -}
thrust_sea_level :
    SelectionSet decodesTo SpaceX.Object.Force
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.RocketEngines
thrust_sea_level object____ =
    Object.selectionForCompositeField "thrust_sea_level" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
thrust_vacuum :
    SelectionSet decodesTo SpaceX.Object.Force
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.RocketEngines
thrust_vacuum object____ =
    Object.selectionForCompositeField "thrust_vacuum" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
thrust_to_weight : SelectionSet (Maybe Float) SpaceX.Object.RocketEngines
thrust_to_weight =
    Object.selectionForField "(Maybe Float)" "thrust_to_weight" [] (Decode.float |> Decode.nullable)
