-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SpaceX.Object.Ship exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SpaceX.InputObject
import SpaceX.Interface
import SpaceX.Object
import SpaceX.Scalar
import SpaceX.ScalarCodecs
import SpaceX.Union


{-| -}
abs : SelectionSet (Maybe Int) SpaceX.Object.Ship
abs =
    Object.selectionForField "(Maybe Int)" "abs" [] (Decode.int |> Decode.nullable)


{-| -}
active : SelectionSet (Maybe Bool) SpaceX.Object.Ship
active =
    Object.selectionForField "(Maybe Bool)" "active" [] (Decode.bool |> Decode.nullable)


{-| -}
attempted_landings : SelectionSet (Maybe Int) SpaceX.Object.Ship
attempted_landings =
    Object.selectionForField "(Maybe Int)" "attempted_landings" [] (Decode.int |> Decode.nullable)


{-| -}
class : SelectionSet (Maybe Int) SpaceX.Object.Ship
class =
    Object.selectionForField "(Maybe Int)" "class" [] (Decode.int |> Decode.nullable)


{-| -}
course_deg : SelectionSet (Maybe Int) SpaceX.Object.Ship
course_deg =
    Object.selectionForField "(Maybe Int)" "course_deg" [] (Decode.int |> Decode.nullable)


{-| -}
home_port : SelectionSet (Maybe String) SpaceX.Object.Ship
home_port =
    Object.selectionForField "(Maybe String)" "home_port" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet (Maybe SpaceX.ScalarCodecs.Id) SpaceX.Object.Ship
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SpaceX.ScalarCodecs.codecs |> SpaceX.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
image : SelectionSet (Maybe String) SpaceX.Object.Ship
image =
    Object.selectionForField "(Maybe String)" "image" [] (Decode.string |> Decode.nullable)


{-| -}
imo : SelectionSet (Maybe Int) SpaceX.Object.Ship
imo =
    Object.selectionForField "(Maybe Int)" "imo" [] (Decode.int |> Decode.nullable)


{-| -}
missions :
    SelectionSet decodesTo SpaceX.Object.ShipMission
    -> SelectionSet (Maybe (List (Maybe decodesTo))) SpaceX.Object.Ship
missions object____ =
    Object.selectionForCompositeField "missions" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
mmsi : SelectionSet (Maybe Int) SpaceX.Object.Ship
mmsi =
    Object.selectionForField "(Maybe Int)" "mmsi" [] (Decode.int |> Decode.nullable)


{-| -}
model : SelectionSet (Maybe String) SpaceX.Object.Ship
model =
    Object.selectionForField "(Maybe String)" "model" [] (Decode.string |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) SpaceX.Object.Ship
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
position :
    SelectionSet decodesTo SpaceX.Object.ShipLocation
    -> SelectionSet (Maybe decodesTo) SpaceX.Object.Ship
position object____ =
    Object.selectionForCompositeField "position" [] object____ (Basics.identity >> Decode.nullable)


{-| -}
roles : SelectionSet (Maybe (List (Maybe String))) SpaceX.Object.Ship
roles =
    Object.selectionForField "(Maybe (List (Maybe String)))" "roles" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
speed_kn : SelectionSet (Maybe Float) SpaceX.Object.Ship
speed_kn =
    Object.selectionForField "(Maybe Float)" "speed_kn" [] (Decode.float |> Decode.nullable)


{-| -}
status : SelectionSet (Maybe String) SpaceX.Object.Ship
status =
    Object.selectionForField "(Maybe String)" "status" [] (Decode.string |> Decode.nullable)


{-| -}
successful_landings : SelectionSet (Maybe Int) SpaceX.Object.Ship
successful_landings =
    Object.selectionForField "(Maybe Int)" "successful_landings" [] (Decode.int |> Decode.nullable)


{-| -}
type_ : SelectionSet (Maybe String) SpaceX.Object.Ship
type_ =
    Object.selectionForField "(Maybe String)" "type" [] (Decode.string |> Decode.nullable)


{-| -}
url : SelectionSet (Maybe String) SpaceX.Object.Ship
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


{-| -}
weight_kg : SelectionSet (Maybe Int) SpaceX.Object.Ship
weight_kg =
    Object.selectionForField "(Maybe Int)" "weight_kg" [] (Decode.int |> Decode.nullable)


{-| -}
weight_lbs : SelectionSet (Maybe Int) SpaceX.Object.Ship
weight_lbs =
    Object.selectionForField "(Maybe Int)" "weight_lbs" [] (Decode.int |> Decode.nullable)


{-| -}
year_built : SelectionSet (Maybe Int) SpaceX.Object.Ship
year_built =
    Object.selectionForField "(Maybe Int)" "year_built" [] (Decode.int |> Decode.nullable)
